import { ContactBand } from "@/app/components/ContactBand";
import { InnerHero } from "@/app/components/InnerHero";
import { createPageMetadata } from "@/app/lib/metadata";

export const metadata = createPageMetadata({ title: "Company", description: "Dawood Technologies developed from the technology needs of operating businesses and brings that ownership-driven approach to other organizations.", path: "/company" });
export default function CompanyPage() {
  return <main id="main-content"><InnerHero kicker="COMPANY" title="Technology capability built from operating experience." intro="Dawood Technologies developed from the technology responsibilities of Dawood operating businesses and extends that ownership-driven approach to other organizations." />
    <section className="section company-story"><div className="container story-grid"><div><p className="kicker">BUILT FROM OPERATING EXPERIENCE</p><h2>Technology responsibility became a dedicated company.</h2></div><div className="story-copy"><p>Dawood Technologies was established from the technology needs of Dawood operating businesses. What began as an internal capability to manage applications, infrastructure, systems, security, data and day-to-day technology operations developed into a dedicated technology company.</p><p>Today, Dawood Technologies brings that ownership-driven approach to organizations beyond Dawood, designing, building, modernizing and supporting technology around how businesses actually operate.</p><p>The Dawood name reflects this operating-business heritage and the practical responsibilities that shaped the company&apos;s approach.</p></div></div></section>
    <section className="section company-engineering"><div className="container story-grid"><div><p className="kicker">ENGINEERING ACROSS THE TECHNOLOGY LIFECYCLE</p><h2>Multidisciplinary capability behind the work.</h2></div><div className="story-copy"><p>Our team brings together engineers and technology professionals across application development, cloud infrastructure, data, enterprise systems, automation, cybersecurity and technology operations.</p><p>These disciplines are considered together so that decisions made during architecture and engineering remain practical through deployment, operation and support.</p></div></div></section>
    <section className="section ownership-section"><div className="container"><div className="split-heading"><div><p className="kicker">TECHNOLOGY OWNERSHIP BEYOND DELIVERY</p><h2>An operating responsibility, not simply a delivery milestone.</h2></div><p>Architecture, implementation, deployment, security, maintainability, support and continuous improvement are considered as parts of the same technology lifecycle.</p></div><ol className="ownership-flow"><li><span>01</span><strong>Strategy</strong></li><li><span>02</span><strong>Architecture</strong></li><li><span>03</span><strong>Engineering</strong></li><li><span>04</span><strong>Deployment</strong></li><li><span>05</span><strong>Operations</strong></li><li><span>06</span><strong>Support</strong></li><li><span>07</span><strong>Continuous improvement</strong></li></ol></div></section>
    <section className="section principles"><div className="container"><p className="kicker">HOW WE WORK</p><div className="principle-grid"><article><span>01</span><h3>Operational alignment</h3><p>Decisions start with how the business works, not with a preferred tool.</p></article><article><span>02</span><h3>Technology ownership</h3><p>Systems should be understandable, maintainable and supported over time.</p></article><article><span>03</span><h3>Security by design</h3><p>Access, resilience and risk belong inside the solution from the beginning.</p></article><article><span>04</span><h3>Continuous improvement</h3><p>Technology evolves alongside the operation rather than standing still after launch.</p></article></div></div></section>
    <ContactBand /></main>;
}
